import io

from docx import Document
from docx.shared import Pt, RGBColor

from extractor import CLAUSE_TYPES, DATE_FIELDS
from labels import CLAUSE_LABELS, DATE_LABELS
from risk_score import compute_risk_score

DISCLAIMER = (
    "This memo was generated by an AI contract-review assistant. It is a drafting aid for "
    "internal triage, not legal advice. Have a qualified attorney review all flagged clauses "
    "and suggested language before relying on or sending this document."
)


def _add_heading(doc, text, size=14, color=(42, 39, 33)):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(size)
    run.font.color.rgb = RGBColor(*color)
    return p


def build_memo(result, contract_name, mode="plain"):
    """Returns a BytesIO containing a .docx negotiation/review memo."""
    summary_key = "summary_legal" if mode == "legal" else "summary_plain"
    reason_key = "flag_reason_legal" if mode == "legal" else "flag_reason_plain"

    risk = compute_risk_score(result)

    doc = Document()
    _add_heading(doc, "Contract Review Memo", size=18)
    doc.add_paragraph(f"Contract: {contract_name}  ({result.get('contract_type_guess', 'Unknown type')})")
    doc.add_paragraph(f"Risk Score: {risk['score']} / 100 — {risk['label']}")
    doc.add_paragraph("")

    _add_heading(doc, "Key Dates")
    for field in DATE_FIELDS:
        entry = result["dates"][field]
        if entry["found"] and entry["date"]:
            doc.add_paragraph(f"• {DATE_LABELS[field]}: {entry['date']}")
        else:
            doc.add_paragraph(f"• {DATE_LABELS[field]}: not stated in contract")
    doc.add_paragraph("")

    flagged = [ct for ct in CLAUSE_TYPES if result["clauses"][ct]["flagged"]]
    standard = [ct for ct in CLAUSE_TYPES if result["clauses"][ct]["found"] and not result["clauses"][ct]["flagged"]]
    not_found = [ct for ct in CLAUSE_TYPES if not result["clauses"][ct]["found"]]

    _add_heading(doc, f"Flagged Issues ({len(flagged)})", color=(178, 59, 59))
    if not flagged:
        doc.add_paragraph("None — no clauses deviated from the playbook's acceptable range.")
    for ct in flagged:
        c = result["clauses"][ct]
        doc.add_paragraph(f"{CLAUSE_LABELS[ct]}").runs[0].bold = True
        quote_p = doc.add_paragraph(f"Quoted language: “{c['quote']}”")
        quote_p.runs[0].italic = True
        doc.add_paragraph(f"Issue: {c.get(reason_key) or ''}")
        if c.get("suggested_redline"):
            p = doc.add_paragraph()
            run = p.add_run(f"Suggested replacement: {c['suggested_redline']}")
            run.italic = True
        doc.add_paragraph("")

    _add_heading(doc, f"Standard Clauses ({len(standard)})", color=(12, 163, 12))
    for ct in standard:
        c = result["clauses"][ct]
        doc.add_paragraph(f"• {CLAUSE_LABELS[ct]}: {c.get(summary_key) or ''}")
    doc.add_paragraph("")

    _add_heading(doc, f"Not Found ({len(not_found)})", color=(138, 133, 119))
    for ct in not_found:
        doc.add_paragraph(f"• {CLAUSE_LABELS[ct]}")
    doc.add_paragraph("")

    _add_heading(doc, "Disclaimer", size=11, color=(138, 133, 119))
    disclaimer_p = doc.add_paragraph(DISCLAIMER)
    disclaimer_p.runs[0].italic = True

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
